### ISSUE TITLE
[External objects] Using the 'Extract zip file' button results in Error 500

### ISSUE THREAD

**Issue by andreibosco** [maxSIMhealth/GEN#483]
On the Admin UI, when trying to extract an uploaded external object using the 'Extract zip file' results in Error 500 page.

**Comment by andreibosco** [comment]
Server log:
```
[gen] [2023-03-24 12:21:20] 2023-03-24 12:21:20,946 ERROR [django.request:241] log 3 140135486679864 Internal Server Error: /en/admin/content/externalobject/
[gen] [2023-03-24 12:21:20] Traceback (most recent call last):
[gen] [2023-03-24 12:21:20]   File "/env/lib/python3.10/site-packages/asgiref/sync.py", line 486, in thread_handler
[gen] [2023-03-24 12:21:20]     raise exc_info[1]
[gen] [2023-03-24 12:21:20]   File "/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 43, in inner
[gen] [2023-03-24 12:21:20]     response = await get_response(request)
[gen] [2023-03-24 12:21:20]   File "/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
[gen] [2023-03-24 12:21:20]     response = await wrapped_callback(
[gen] [2023-03-24 12:21:20]   File "/env/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
[gen] [2023-03-24 12:21:20]     ret = await asyncio.wait_for(future, timeout=None)
[gen] [2023-03-24 12:21:20]   File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
[gen] [2023-03-24 12:21:20]     return await fut
[gen] [2023-03-24 12:21:20]   File "/env/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
[gen] [2023-03-24 12:21:20]     result = self.fn(*self.args, **self.kwargs)
[gen] [2023-03-24 12:21:20]   File "/env/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
[gen] [2023-03-24 12:21:20]     return func(*args, **kwargs)
[gen] [2023-03-24 12:21:20]   File "/env/lib/python3.10/site-packages/django/contrib/admin/options.py", line 683, in wrapper
[gen] [2023-03-24 12:21:20]     return self.admin_site.admin_view(view)(*args, **kwargs)
[gen] [2023-03-24 12:21:20]   File "/env/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
[gen] [2023-03-24 12:21:20]     response = view_func(request, *args, **kwargs)
[gen] [2023-03-24 12:21:20]   File "/env/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
[gen] [2023-03-24 12:21:20]     response = view_func(request, *args, **kwargs)
[gen] [2023-03-24 12:21:20]   File "/env/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
[gen] [2023-03-24 12:21:20]     return view(request, *args, **kwargs)
[gen] [2023-03-24 12:21:20]   File "/env/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
[gen] [2023-03-24 12:21:20]     return bound_method(*args, **kwargs)
[gen] [2023-03-24 12:21:20]   File "/env/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
[gen] [2023-03-24 12:21:20]     response = view_func(request, *args, **kwargs)
[gen] [2023-03-24 12:21:20]   File "/env/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1960, in changelist_view
[gen] [2023-03-24 12:21:20]     response = self.response_action(
[gen] [2023-03-24 12:21:20]   File "/env/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1589, in response_action
[gen] [2023-03-24 12:21:20]     response = func(self, request, queryset)
[gen] [2023-03-24 12:21:20]   File "/gen/app/content/admin.py", line 29, in duplicate_with_file
[gen] [2023-03-24 12:21:20]     item.duplicate(suffix="(copy)", published=False, file=True)
[gen] [2023-03-24 12:21:20] AttributeError: 'ExternalObject' object has no attribute 'duplicate'
[gen] [2023-03-24 12:39:49] 2023-03-24 12:39:49,245 ERROR [django.request:241] log 3 140135485631288 Internal Server Error: /en/admin/content/externalobject/70/change/
[gen] [2023-03-24 12:39:49] Traceback (most recent call last):
[gen] [2023-03-24 12:39:49]   File "/env/lib/python3.10/site-packages/asgiref/sync.py", line 486, in thread_handler
[gen] [2023-03-24 12:39:49]     raise exc_info[1]
[gen] [2023-03-24 12:39:49]   File "/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 43, in inner
[gen] [2023-03-24 12:39:49]     response = await get_response(request)
[gen] [2023-03-24 12:39:49]   File "/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
[gen] [2023-03-24 12:39:49]     response = await wrapped_callback(
[gen] [2023-03-24 12:39:49]   File "/env/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
[gen] [2023-03-24 12:39:49]     ret = await asyncio.wait_for(future, timeout=None)
[gen] [2023-03-24 12:39:49]   File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
[gen] [2023-03-24 12:39:49]     return await fut
[gen] [2023-03-24 12:39:49]   File "/env/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
[gen] [2023-03-24 12:39:49]     result = self.fn(*self.args, **self.kwargs)
[gen] [2023-03-24 12:39:49]   File "/env/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
[gen] [2023-03-24 12:39:49]     return func(*args, **kwargs)
[gen] [2023-03-24 12:39:49]   File "/env/lib/python3.10/site-packages/django/contrib/admin/options.py", line 683, in wrapper
[gen] [2023-03-24 12:39:49]     return self.admin_site.admin_view(view)(*args, **kwargs)
[gen] [2023-03-24 12:39:49]   File "/env/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
[gen] [2023-03-24 12:39:49]     response = view_func(request, *args, **kwargs)
[gen] [2023-03-24 12:39:49]   File "/env/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
[gen] [2023-03-24 12:39:49]     response = view_func(request, *args, **kwargs)
[gen] [2023-03-24 12:39:49]   File "/env/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
[gen] [2023-03-24 12:39:49]     return view(request, *args, **kwargs)
[gen] [2023-03-24 12:39:49]   File "/env/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1889, in change_view
[gen] [2023-03-24 12:39:49]     return self.changeform_view(request, object_id, form_url, extra_context)
[gen] [2023-03-24 12:39:49]   File "/env/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
[gen] [2023-03-24 12:39:49]     return bound_method(*args, **kwargs)
[gen] [2023-03-24 12:39:49]   File "/env/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
[gen] [2023-03-24 12:39:49]     response = view_func(request, *args, **kwargs)
[gen] [2023-03-24 12:39:49]   File "/env/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1746, in changeform_view
[gen] [2023-03-24 12:39:49]     return self._changeform_view(request, object_id, form_url, extra_context)
[gen] [2023-03-24 12:39:49]   File "/env/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1808, in _changeform_view
[gen] [2023-03-24 12:39:49]     return self.response_change(request, new_object)
[gen] [2023-03-24 12:39:49]   File "/gen/app/content/admin.py", line 224, in response_change
[gen] [2023-03-24 12:39:49]     obj.unzip_package(request)
[gen] [2023-03-24 12:39:49]   File "/gen/app/content/models.py", line 197, in unzip_package
[gen] [2023-03-24 12:39:49]     directory_exists = media_storage.directory_exists(output_path)
[gen] [2023-03-24 12:39:49]   File "/gen/app/GEN/storage_backends.py", line 53, in directory_exists
[gen] [2023-03-24 12:39:49]     path = self._normalize_name((self._clean_name(path))).rstrip("/")
[gen] [2023-03-24 12:39:49] AttributeError: 'MediaStorage' object has no attribute '_clean_name'
[gen] [2023-03-24 14:40:26] 2023-03-24 14:40:26,059 ERROR [django.request:241] log 3 140135466289976 Internal Server Error: /en/admin/content/externalobject/70/change/
[gen] [2023-03-24 14:40:26] Traceback (most recent call last):
[gen] [2023-03-24 14:40:26]   File "/env/lib/python3.10/site-packages/asgiref/sync.py", line 486, in thread_handler
[gen] [2023-03-24 14:40:26]     raise exc_info[1]
[gen] [2023-03-24 14:40:26]   File "/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 43, in inner
[gen] [2023-03-24 14:40:26]     response = await get_response(request)
[gen] [2023-03-24 14:40:26]   File "/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
[gen] [2023-03-24 14:40:26]     response = await wrapped_callback(
[gen] [2023-03-24 14:40:26]   File "/env/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
[gen] [2023-03-24 14:40:26]     ret = await asyncio.wait_for(future, timeout=None)
[gen] [2023-03-24 14:40:26]   File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
[gen] [2023-03-24 14:40:26]     return await fut
[gen] [2023-03-24 14:40:26]   File "/env/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
[gen] [2023-03-24 14:40:26]     result = self.fn(*self.args, **self.kwargs)
[gen] [2023-03-24 14:40:26]   File "/env/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
[gen] [2023-03-24 14:40:26]     return func(*args, **kwargs)
[gen] [2023-03-24 14:40:26]   File "/env/lib/python3.10/site-packages/django/contrib/admin/options.py", line 683, in wrapper
[gen] [2023-03-24 14:40:26]     return self.admin_site.admin_view(view)(*args, **kwargs)
[gen] [2023-03-24 14:40:26]   File "/env/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
[gen] [2023-03-24 14:40:26]     response = view_func(request, *args, **kwargs)
[gen] [2023-03-24 14:40:26]   File "/env/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
[gen] [2023-03-24 14:40:26]     response = view_func(request, *args, **kwargs)
[gen] [2023-03-24 14:40:26]   File "/env/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
[gen] [2023-03-24 14:40:26]     return view(request, *args, **kwargs)
[gen] [2023-03-24 14:40:26]   File "/env/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1889, in change_view
[gen] [2023-03-24 14:40:26]     return self.changeform_view(request, object_id, form_url, extra_context)
[gen] [2023-03-24 14:40:26]   File "/env/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
[gen] [2023-03-24 14:40:26]     return bound_method(*args, **kwargs)
[gen] [2023-03-24 14:40:26]   File "/env/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
[gen] [2023-03-24 14:40:26]     response = view_func(request, *args, **kwargs)
[gen] [2023-03-24 14:40:26]   File "/env/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1746, in changeform_view
[gen] [2023-03-24 14:40:26]     return self._changeform_view(request, object_id, form_url, extra_context)
[gen] [2023-03-24 14:40:26]   File "/env/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1808, in _changeform_view
[gen] [2023-03-24 14:40:26]     return self.response_change(request, new_object)
[gen] [2023-03-24 14:40:26]   File "/gen/app/content/admin.py", line 224, in response_change
[gen] [2023-03-24 14:40:26]     obj.unzip_package(request)
[gen] [2023-03-24 14:40:26]   File "/gen/app/content/models.py", line 197, in unzip_package
[gen] [2023-03-24 14:40:26]     directory_exists = media_storage.directory_exists(output_path)
[gen] [2023-03-24 14:40:26]   File "/gen/app/GEN/storage_backends.py", line 53, in directory_exists
[gen] [2023-03-24 14:40:26]     path = self._normalize_name((self._clean_name(path))).rstrip("/")
[gen] [2023-03-24 14:40:26] AttributeError: 'MediaStorage' object has no attribute '_clean_name'
```
